// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Episode } from "./Episode";

export type Anime = {
  id: string;
  sn: number;
  cover: string;
  cover_id: string | null;
  name: string;
  series: { [key in string]: Array<Episode> };
  create_at: string;
  update_at: string;
};
