// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigVersion = {
  /**
   * 主版本号，主版本号变更时，配置文件将无法兼容旧版本
   */
  major: number;
  /**
   * 次版本号，次版本号变更时，配置文件将可以兼容旧版本
   */
  minor: number;
};
