// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadResolution } from "./DownloadResolution";
import type { InternalConfig } from "./InternalConfig";

export type Config = {
  /**
   * 下载选取清晰度，若该清晰度不存在将会选取最近可用清晰度，可选 360 540 720 1080，默认为 1080。
   */
  download_resolution: DownloadResolution;
  /**
   * 是否锁定清晰度，如果指定清晰度不存在，则放弃下载
   */
  lock_resolution: boolean;
  /**
   * 是否只使用 VIP 账号下载
   */
  only_use_vip: boolean;
  /**
   * 每个视频最大并发下载分段数，仅在 `segment_download_mode` 为 true 时有效，最高为 5，超过将重置为 5。
   * 默认值为 2。
   */
  multi_downloading_segment: number;
  /**
   * 请求UA，需要和获取cookie的浏览器相同
   */
  ua: string;
  /**
   * 代理配置
   */
  proxy: string | null;
  /**
   * 非VIP广告等待时间, 如果等待时间不足, 程序会自行追加时间 (最大20秒)。默认值为 25。
   */
  ads_time: number;
  /**
   * 内部配置，请勿直接修改
   */
  internal: InternalConfig;
};
