// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Episode } from "./Episode";
import type { EpisodeDownloadEvent } from "./EpisodeDownloadEvent";

export type DownloadEvent = {
  episode: Episode;
  state: { Ok: EpisodeDownloadEvent } | { Err: string };
};
