// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Episode = {
  id: string;
  sn: number;
  cover: string;
  cover_id: string | null;
  episode: number;
  create_at: string;
  update_at: string;
};
