// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EpisodeDownloadEvent =
  | { type: "PENDING" }
  | { type: "PREPARING" }
  | { type: "WAITING_FOR_ADS" }
  | { type: "RESOLVE_MEDIA_RESOURCE" }
  | { type: "DOWNLOADING_SEGMENTS"; completed: number; total: number }
  | { type: "MERGING" }
  | { type: "FINALIZING" }
  | { type: "COMPLETED" };
