// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigVersion } from "./ConfigVersion";

export type InternalConfig = {
  /**
   * 配置文件版本
   */
  config_version: ConfigVersion;
};
