// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadResolution } from "./DownloadResolution";
import type { InternalConfig } from "./InternalConfig";

export type SettingsConfig = {
  downloadResolution: DownloadResolution;
  lockResolution: boolean;
  onlyUseVip: boolean;
  multiDownloadingSegment: number;
  ua: string;
  proxy: string | null;
  adsTime: number;
  internal: InternalConfig;
};
