[package]
name = "ani-dock-server"
version = "0.1.0"
edition = "2024"

[dependencies]
ani-dock-core.workspace = true
ani-dock-db.workspace = true
anyhow.workspace = true
axum = { workspace = true, features = ["macros"] }
chrono = { workspace = true, features = ["serde"] }
futures.workspace = true
indexmap.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tokio-stream = { workspace = true, features = ["sync"] }
tokio-util = { workspace = true, features = ["rt"] }
tower-http = { version = "0.7.0", features = ["fs"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
ts-rs.workspace = true
uuid = { workspace = true, features = ["serde"] }
wreq.workspace = true

[dev-dependencies]
serde_json.workspace = true
