[package]
name = "ani-dock-server"
version = "0.1.0"
edition = "2024"

[dependencies]
ani-dock-core.workspace = true
ani-dock-db.workspace = true
axum = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
futures.workspace = true
indexmap.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-stream = { workspace = true, features = ["sync"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
ts-rs.workspace = true
uuid = { workspace = true, features = ["serde"] }
