[package]
name = "ani-dock-db"
version = "0.1.0"
edition = "2024"

[dependencies]
ani-dock-core = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
indexmap.workspace = true
serde.workspace = true
sqlx = {
  workspace = true,
  features = [
    "chrono",
    "runtime-tokio",
    "sqlite",
    "uuid",
  ]
}
tokio = { workspace = true }
ts-rs = { workspace = true, features = ["chrono-impl", "indexmap-impl", "uuid-impl"] }
uuid = { workspace = true, features = ["serde", "v7"] }
