[package]
name = "ani-dock-db"
version = "0.1.0"
edition = "2024"

[dependencies]
ani-dock-core = { workspace = true }
chrono.workspace = true
indexmap.workspace = true
sqlx = { workspace = true, features = ["chrono", "runtime-tokio", "sqlite", "uuid"] }
tokio = { workspace = true }
uuid = { workspace = true, features = ["v7"] }
