-- Add migration script here
CREATE TABLE IF NOT EXISTS anime (
  id TEXT PRIMARY KEY NOT NULL,
  sn INTEGER NOT NULL UNIQUE,
  cover TEXT NOT NULL,
  create_at TEXT NOT NULL,
  update_at TEXT NOT NULL
) WITHOUT ROWID, STRICT;

CREATE TABLE IF NOT EXISTS series (
  id TEXT PRIMARY KEY NOT NULL,
  anime_id TEXT NOT NULL REFERENCES anime(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  create_at TEXT NOT NULL,
  update_at TEXT NOT NULL,

  UNIQUE (anime_id, name)
) WITHOUT ROWID, STRICT;

CREATE TABLE IF NOT EXISTS episode (
  id TEXT PRIMARY KEY NOT NULL,
  series_id TEXT NOT NULL REFERENCES series(id) ON DELETE CASCADE,
  sn INTEGER NOT NULL UNIQUE,
  cover TEXT NOT NULL,
  episode INTEGER NOT NULL,
  create_at TEXT NOT NULL,
  update_at TEXT NOT NULL
) WITHOUT ROWID, STRICT;
